web:
  image: tutum/apache-php
  ports:
    - "80:80"
  volumes:
    - /var/www/mml:/var/www/
    - /var/www/docker/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
    - /var/www/docker/sites:/etc/apache2/sites-enabled
  environment:
    - ALLOW_OVERRIDE=true
  links:
    - db:db

  # image: nginx
  # ports:
  #   - "80:80"
  # volumes:
  #   - /var/wwww/docker/nginx:/etc/nginx/conf.d
  #   - /var/www/mml:/var/www/mml
  # links:
  #   - php:php

# php:
#   image: php:7.1.10-fpm
#   volumes:
#     - /var/www:/var/www/html
#   links:
#     - db:db


db:
  image: mysql
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD= root
    - MYSQL_DATABASE= dev_mml
    - MYSQL_USER= root
    - MYSQL_PASSWORD= root

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
     - "8080:80"
  links:
      - db:db

